### PR TITLE
Update dynamo db store documenation

### PR DESCRIPTION
**Pull request by ChristopherMcKenzie**
Updating documention in relation to this PR, dotnet/orleans#7104

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/orleans-docs?pullRequest=58) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/orleans-docs?pullRequest=58) before we can accept your contribution.<br/><br/>:x: ChristopherMcKenzie [sign now](https://cla.dotnetfoundation.org/dotnet/orleans-docs?pullRequest=58)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/orleans-docs?pullRequest=58) it.</sub>

**Comment by bradygaster** [comment]
Docs Build status updates of commit _[e984904](https://github.com/ChristopherMcKenzie/orleans-docs/commits/e9849049c474f3ef54f574f581f1b9448c00a6f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[src/docs/grains/grain_persistence/dynamodb_storage.md](https://github.com/ChristopherMcKenzie/orleans-docs/blob/Update-DynamoDB-Store-documenation/src/docs/grains/grain_persistence/dynamodb_storage.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/dotnet/orleans/grains/grain_persistence/dynamodb_storage?branch=pr-en-us-58) | [Details](#user-content-3202834b9cf399b23de6a8f8fa803053-62683a17)

<a id="3202834b9cf399b23de6a8f8fa803053-62683a17"></a>
### [src/docs/grains/grain_persistence/dynamodb_storage.md](https://github.com/ChristopherMcKenzie/orleans-docs/blob/Update-DynamoDB-Store-documenation/src/docs/grains/grain_persistence/dynamodb_storage.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C1%5C6ed070cb-39dc-476e-9157-4a841077fa5e%5CPullRequest%5C202112011116235916-58%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-01T11%3A17%3A03Z&sr=b&sp=r&sig=mhYpTdg3tX6lIs%2FUM7ZKPhbr%2BS%2BBIbm95mRQOX3lHGE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ed070cb-39dc-476e-9157-4a841077fa5e?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by ChristopherMcKenzie** [comment]
I don't have access to any these links you've replied with, with the exception of the build report. Would you be able to provide a little more information into the 'description' aspect of things I'm missing.

**Comment by IEvangelist** [comment]
Closed by https://github.com/dotnet/docs/pull/28582

**Pull request closed without merging**
