### PR TITLE
Update stream_providers.md

### PR DESCRIPTION
**Pull request by kpko**
Corrected a few broken links (Streaming components moved into their own package)

### CODE REVIEW

**Comment by bradygaster** [comment]
Docs Build status updates of commit _[f05729b](https://github.com/kpko/orleans-docs/commits/f05729bc4ab8967b79eef33e6ebff11217ce3ce3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[src/docs/streaming/stream_providers.md](https://github.com/kpko/orleans-docs/blob/patch-1/src/docs/streaming/stream_providers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/dotnet/orleans-old/streaming/stream_providers?branch=pr-en-us-65) | [Details](#user-content-7ea744382af5d129419f5a36b042cc2f-5f92a955)

<a id="7ea744382af5d129419f5a36b042cc2f-5f92a955"></a>
### [src/docs/streaming/stream_providers.md](https://github.com/kpko/orleans-docs/blob/patch-1/src/docs/streaming/stream_providers.md)
 - **Line 44, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/docs/implementation/streams_implementation/index.md'.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C6ed070cb-39dc-476e-9157-4a841077fa5e%5CPullRequest%5C202202231553554843-65%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T15%3A54%3A48Z&sr=b&sp=r&sig=fwnQUbmK%2B3Cl27KVogH9p6X%2FnpYIZMPxXRrthCuvgBI%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ed070cb-39dc-476e-9157-4a841077fa5e?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by kpko** [comment]
Hi,

it seems like the links are already fixed at https://docs.microsoft.com/en-us/dotnet/orleans/streaming/stream-providers but not at https://dotnet.github.io/orleans/docs/streaming/stream_providers.html. I'm new to Orleans and the first documentation I found googling was the second, non-functional link. Are these two documentations somehow kept in sync? If not, should the "old" documentation at dotnet.github.com/orleans/ not redirect to the new documentation at docs.microsoft.com? See https://github.com/dotnet/orleans-docs/issues/66 too.

**Comment by ReubenBond** [comment]
Hi Kevin, we will need to archive this repo and update the old docs pages with redirection to the new pages manually (likely using <meta> tags). Apologies for the delay in getting to this Pr and others

**Comment by IEvangelist** [comment]
Closed by https://github.com/dotnet/docs/pull/28582

**Pull request closed without merging**
